sudo: required
services:
  - docker
before_install:
  - docker build -t jatinder031/react-test -f ./client/Dockerfile.dev ./client

script:

  - docker run -e CI=true jatinder031/react-test npm test -- --coverage


after_success:

  - docker build -t jatinder031/multi-client ./client
  - docker build -t jatinder031/multi-nginx ./nginx
  - docker build -t jatinder031/multi-server ./server
  - docker build -t jatinder031/multi-worker ./worker





